# SwiftLint Configuration for Intok iOS App

excluded:
  - Pods
  - build
  - DerivedData
  - .build

disabled_rules:
  - trailing_whitespace
  - line_length
  - todo
  - trailing_newline
  - multiple_closures_with_trailing_closure
  - implicit_optional_initialization

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - fallthrough
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - yoda_condition

line_length:
  warning: 150
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 2
  function_level: 3

identifier_name:
  min_length: 1
  max_length: 50
  excluded:
    - id

type_name:
  min_length: 3
  max_length: 50

reporter: "xcode"
