// Emoji data with searchable names
export interface EmojiData {
  emoji: string;
  name: string;
  keywords: string[];
  category: string;
}

export const EMOJI_CATEGORIES = [
  'Frequently Used',
  'Smileys',
  'Gestures',
  'People',
  'Animals',
  'Food',
  'Activities',
  'Travel',
  'Objects',
  'Symbols',
] as const;

export type EmojiCategory = typeof EMOJI_CATEGORIES[number];

// Frequently used emojis (shown first, quick access)
export const FREQUENT_EMOJIS = ['❤️', '👍', '😂', '😊', '🔥', '💯', '🎉', '👏', '😍', '🤔', '😢', '😡'];

// Full emoji list with searchable metadata
export const EMOJIS: EmojiData[] = [
  // Smileys & Emotion
  { emoji: '😀', name: 'grinning face', keywords: ['smile', 'happy', 'joy'], category: 'Smileys' },
  { emoji: '😃', name: 'grinning face with big eyes', keywords: ['smile', 'happy', 'joy'], category: 'Smileys' },
  { emoji: '😄', name: 'grinning face with smiling eyes', keywords: ['smile', 'happy', 'joy'], category: 'Smileys' },
  { emoji: '😁', name: 'beaming face', keywords: ['smile', 'happy', 'grin'], category: 'Smileys' },
  { emoji: '😆', name: 'grinning squinting face', keywords: ['laugh', 'happy', 'haha'], category: 'Smileys' },
  { emoji: '😅', name: 'grinning face with sweat', keywords: ['nervous', 'laugh', 'sweat'], category: 'Smileys' },
  { emoji: '😂', name: 'face with tears of joy', keywords: ['laugh', 'cry', 'happy', 'lol', 'funny'], category: 'Smileys' },
  { emoji: '🤣', name: 'rolling on floor laughing', keywords: ['laugh', 'lol', 'rofl', 'funny'], category: 'Smileys' },
  { emoji: '☺️', name: 'smiling face', keywords: ['smile', 'happy', 'blush'], category: 'Smileys' },
  { emoji: '😊', name: 'smiling face with smiling eyes', keywords: ['smile', 'happy', 'blush', 'cute'], category: 'Smileys' },
  { emoji: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent', 'blessed'], category: 'Smileys' },
  { emoji: '🙂', name: 'slightly smiling face', keywords: ['smile', 'okay'], category: 'Smileys' },
  { emoji: '🙃', name: 'upside-down face', keywords: ['silly', 'sarcasm'], category: 'Smileys' },
  { emoji: '😉', name: 'winking face', keywords: ['wink', 'flirt'], category: 'Smileys' },
  { emoji: '😍', name: 'smiling face with heart-eyes', keywords: ['love', 'crush', 'heart'], category: 'Smileys' },
  { emoji: '🥰', name: 'smiling face with hearts', keywords: ['love', 'adore', 'hearts'], category: 'Smileys' },
  { emoji: '😘', name: 'face blowing a kiss', keywords: ['kiss', 'love', 'flirt'], category: 'Smileys' },
  { emoji: '😗', name: 'kissing face', keywords: ['kiss'], category: 'Smileys' },
  { emoji: '😙', name: 'kissing face with smiling eyes', keywords: ['kiss', 'happy'], category: 'Smileys' },
  { emoji: '😋', name: 'face savoring food', keywords: ['yummy', 'delicious', 'tongue'], category: 'Smileys' },
  { emoji: '😛', name: 'face with tongue', keywords: ['tongue', 'playful', 'silly'], category: 'Smileys' },
  { emoji: '😜', name: 'winking face with tongue', keywords: ['wink', 'tongue', 'silly', 'crazy'], category: 'Smileys' },
  { emoji: '🤪', name: 'zany face', keywords: ['crazy', 'wild', 'silly'], category: 'Smileys' },
  { emoji: '😝', name: 'squinting face with tongue', keywords: ['tongue', 'playful'], category: 'Smileys' },
  { emoji: '🤑', name: 'money-mouth face', keywords: ['money', 'rich', 'dollar'], category: 'Smileys' },
  { emoji: '🤗', name: 'hugging face', keywords: ['hug', 'embrace', 'love'], category: 'Smileys' },
  { emoji: '🤭', name: 'face with hand over mouth', keywords: ['oops', 'giggle', 'secret'], category: 'Smileys' },
  { emoji: '🤫', name: 'shushing face', keywords: ['quiet', 'secret', 'shh'], category: 'Smileys' },
  { emoji: '🤔', name: 'thinking face', keywords: ['think', 'hmm', 'consider'], category: 'Smileys' },
  { emoji: '🤐', name: 'zipper-mouth face', keywords: ['secret', 'quiet', 'zip'], category: 'Smileys' },
  { emoji: '🤨', name: 'face with raised eyebrow', keywords: ['skeptical', 'suspicious'], category: 'Smileys' },
  { emoji: '😐', name: 'neutral face', keywords: ['meh', 'blank', 'indifferent'], category: 'Smileys' },
  { emoji: '😑', name: 'expressionless face', keywords: ['blank', 'meh'], category: 'Smileys' },
  { emoji: '😶', name: 'face without mouth', keywords: ['silent', 'speechless'], category: 'Smileys' },
  { emoji: '😏', name: 'smirking face', keywords: ['smirk', 'smug', 'flirt'], category: 'Smileys' },
  { emoji: '😒', name: 'unamused face', keywords: ['meh', 'unhappy', 'annoyed'], category: 'Smileys' },
  { emoji: '🙄', name: 'face with rolling eyes', keywords: ['eyeroll', 'annoyed', 'whatever'], category: 'Smileys' },
  { emoji: '😬', name: 'grimacing face', keywords: ['awkward', 'nervous'], category: 'Smileys' },
  { emoji: '😮‍💨', name: 'face exhaling', keywords: ['sigh', 'relief', 'tired'], category: 'Smileys' },
  { emoji: '🤥', name: 'lying face', keywords: ['lie', 'pinocchio'], category: 'Smileys' },
  { emoji: '😌', name: 'relieved face', keywords: ['relief', 'peaceful', 'calm'], category: 'Smileys' },
  { emoji: '😔', name: 'pensive face', keywords: ['sad', 'thoughtful'], category: 'Smileys' },
  { emoji: '😪', name: 'sleepy face', keywords: ['tired', 'sleep'], category: 'Smileys' },
  { emoji: '🤤', name: 'drooling face', keywords: ['drool', 'yummy'], category: 'Smileys' },
  { emoji: '😴', name: 'sleeping face', keywords: ['sleep', 'zzz', 'tired'], category: 'Smileys' },
  { emoji: '😷', name: 'face with medical mask', keywords: ['sick', 'mask', 'covid'], category: 'Smileys' },
  { emoji: '🤒', name: 'face with thermometer', keywords: ['sick', 'fever', 'ill'], category: 'Smileys' },
  { emoji: '🤕', name: 'face with head-bandage', keywords: ['hurt', 'injured'], category: 'Smileys' },
  { emoji: '🤢', name: 'nauseated face', keywords: ['sick', 'vomit', 'gross'], category: 'Smileys' },
  { emoji: '🤮', name: 'face vomiting', keywords: ['sick', 'vomit', 'gross'], category: 'Smileys' },
  { emoji: '🤧', name: 'sneezing face', keywords: ['sick', 'sneeze', 'achoo'], category: 'Smileys' },
  { emoji: '🥵', name: 'hot face', keywords: ['hot', 'heat', 'sweating'], category: 'Smileys' },
  { emoji: '🥶', name: 'cold face', keywords: ['cold', 'freezing'], category: 'Smileys' },
  { emoji: '🥴', name: 'woozy face', keywords: ['drunk', 'dizzy'], category: 'Smileys' },
  { emoji: '😵', name: 'dizzy face', keywords: ['dizzy', 'dead'], category: 'Smileys' },
  { emoji: '🤯', name: 'exploding head', keywords: ['mind blown', 'shocked', 'wow'], category: 'Smileys' },
  { emoji: '🤠', name: 'cowboy hat face', keywords: ['cowboy', 'western'], category: 'Smileys' },
  { emoji: '🥳', name: 'partying face', keywords: ['party', 'celebrate', 'birthday'], category: 'Smileys' },
  { emoji: '🥸', name: 'disguised face', keywords: ['disguise', 'glasses', 'nose'], category: 'Smileys' },
  { emoji: '😎', name: 'smiling face with sunglasses', keywords: ['cool', 'sunglasses', 'awesome'], category: 'Smileys' },
  { emoji: '🤓', name: 'nerd face', keywords: ['nerd', 'geek', 'glasses'], category: 'Smileys' },
  { emoji: '🧐', name: 'face with monocle', keywords: ['curious', 'thinking', 'smart'], category: 'Smileys' },
  { emoji: '😕', name: 'confused face', keywords: ['confused', 'unsure'], category: 'Smileys' },
  { emoji: '😟', name: 'worried face', keywords: ['worried', 'nervous', 'concerned'], category: 'Smileys' },
  { emoji: '🙁', name: 'slightly frowning face', keywords: ['sad', 'frown'], category: 'Smileys' },
  { emoji: '☹️', name: 'frowning face', keywords: ['sad', 'frown', 'unhappy'], category: 'Smileys' },
  { emoji: '😮', name: 'face with open mouth', keywords: ['surprised', 'wow', 'shocked'], category: 'Smileys' },
  { emoji: '😯', name: 'hushed face', keywords: ['surprised', 'quiet'], category: 'Smileys' },
  { emoji: '😲', name: 'astonished face', keywords: ['shocked', 'surprised', 'wow'], category: 'Smileys' },
  { emoji: '😳', name: 'flushed face', keywords: ['embarrassed', 'blush', 'shy'], category: 'Smileys' },
  { emoji: '🥺', name: 'pleading face', keywords: ['please', 'puppy eyes', 'cute', 'beg'], category: 'Smileys' },
  { emoji: '😦', name: 'frowning face with open mouth', keywords: ['sad', 'shocked'], category: 'Smileys' },
  { emoji: '😧', name: 'anguished face', keywords: ['stressed', 'worried'], category: 'Smileys' },
  { emoji: '😨', name: 'fearful face', keywords: ['scared', 'fear', 'afraid'], category: 'Smileys' },
  { emoji: '😰', name: 'anxious face with sweat', keywords: ['nervous', 'anxious', 'worried'], category: 'Smileys' },
  { emoji: '😥', name: 'sad but relieved face', keywords: ['sad', 'relieved', 'sweat'], category: 'Smileys' },
  { emoji: '😢', name: 'crying face', keywords: ['cry', 'sad', 'tear'], category: 'Smileys' },
  { emoji: '😭', name: 'loudly crying face', keywords: ['cry', 'sob', 'sad', 'tears'], category: 'Smileys' },
  { emoji: '😱', name: 'face screaming in fear', keywords: ['scared', 'scream', 'horror'], category: 'Smileys' },
  { emoji: '😖', name: 'confounded face', keywords: ['frustrated', 'confused'], category: 'Smileys' },
  { emoji: '😣', name: 'persevering face', keywords: ['struggle', 'frustrated'], category: 'Smileys' },
  { emoji: '😞', name: 'disappointed face', keywords: ['sad', 'disappointed'], category: 'Smileys' },
  { emoji: '😓', name: 'downcast face with sweat', keywords: ['sad', 'tired', 'sweat'], category: 'Smileys' },
  { emoji: '😩', name: 'weary face', keywords: ['tired', 'frustrated'], category: 'Smileys' },
  { emoji: '😫', name: 'tired face', keywords: ['tired', 'exhausted'], category: 'Smileys' },
  { emoji: '🥱', name: 'yawning face', keywords: ['tired', 'sleepy', 'bored'], category: 'Smileys' },
  { emoji: '😤', name: 'face with steam from nose', keywords: ['angry', 'frustrated', 'triumph'], category: 'Smileys' },
  { emoji: '😡', name: 'pouting face', keywords: ['angry', 'mad', 'rage'], category: 'Smileys' },
  { emoji: '😠', name: 'angry face', keywords: ['angry', 'mad'], category: 'Smileys' },
  { emoji: '🤬', name: 'face with symbols on mouth', keywords: ['angry', 'swear', 'curse'], category: 'Smileys' },
  { emoji: '😈', name: 'smiling face with horns', keywords: ['devil', 'evil', 'mischief'], category: 'Smileys' },
  { emoji: '👿', name: 'angry face with horns', keywords: ['devil', 'angry', 'evil'], category: 'Smileys' },
  { emoji: '💀', name: 'skull', keywords: ['dead', 'death', 'skeleton'], category: 'Smileys' },
  { emoji: '☠️', name: 'skull and crossbones', keywords: ['dead', 'danger', 'pirate'], category: 'Smileys' },
  { emoji: '💩', name: 'pile of poo', keywords: ['poop', 'shit', 'crap'], category: 'Smileys' },
  { emoji: '🤡', name: 'clown face', keywords: ['clown', 'silly'], category: 'Smileys' },
  { emoji: '👹', name: 'ogre', keywords: ['monster', 'scary'], category: 'Smileys' },
  { emoji: '👺', name: 'goblin', keywords: ['monster', 'scary'], category: 'Smileys' },
  { emoji: '👻', name: 'ghost', keywords: ['ghost', 'halloween', 'spooky'], category: 'Smileys' },
  { emoji: '👽', name: 'alien', keywords: ['alien', 'ufo', 'space'], category: 'Smileys' },
  { emoji: '👾', name: 'alien monster', keywords: ['alien', 'game', 'space invader'], category: 'Smileys' },
  { emoji: '🤖', name: 'robot', keywords: ['robot', 'bot', 'machine'], category: 'Smileys' },
  { emoji: '🎃', name: 'jack-o-lantern', keywords: ['halloween', 'pumpkin'], category: 'Smileys' },
  { emoji: '😺', name: 'grinning cat', keywords: ['cat', 'happy'], category: 'Smileys' },
  { emoji: '😸', name: 'grinning cat with smiling eyes', keywords: ['cat', 'happy'], category: 'Smileys' },
  { emoji: '😹', name: 'cat with tears of joy', keywords: ['cat', 'laugh'], category: 'Smileys' },
  { emoji: '😻', name: 'smiling cat with heart-eyes', keywords: ['cat', 'love'], category: 'Smileys' },
  { emoji: '😼', name: 'cat with wry smile', keywords: ['cat', 'smirk'], category: 'Smileys' },
  { emoji: '😽', name: 'kissing cat', keywords: ['cat', 'kiss'], category: 'Smileys' },
  { emoji: '🙀', name: 'weary cat', keywords: ['cat', 'shocked'], category: 'Smileys' },
  { emoji: '😿', name: 'crying cat', keywords: ['cat', 'sad', 'cry'], category: 'Smileys' },
  { emoji: '😾', name: 'pouting cat', keywords: ['cat', 'angry'], category: 'Smileys' },

  // Gestures
  { emoji: '👍', name: 'thumbs up', keywords: ['like', 'yes', 'good', 'approve', 'ok'], category: 'Gestures' },
  { emoji: '👎', name: 'thumbs down', keywords: ['dislike', 'no', 'bad', 'disapprove'], category: 'Gestures' },
  { emoji: '👏', name: 'clapping hands', keywords: ['clap', 'applause', 'bravo'], category: 'Gestures' },
  { emoji: '🙌', name: 'raising hands', keywords: ['celebrate', 'praise', 'hooray'], category: 'Gestures' },
  { emoji: '👐', name: 'open hands', keywords: ['hands', 'open'], category: 'Gestures' },
  { emoji: '🤲', name: 'palms up together', keywords: ['hands', 'prayer'], category: 'Gestures' },
  { emoji: '🤝', name: 'handshake', keywords: ['deal', 'agree', 'shake'], category: 'Gestures' },
  { emoji: '🙏', name: 'folded hands', keywords: ['pray', 'please', 'thanks', 'namaste'], category: 'Gestures' },
  { emoji: '✌️', name: 'victory hand', keywords: ['peace', 'v', 'victory'], category: 'Gestures' },
  { emoji: '🤞', name: 'crossed fingers', keywords: ['luck', 'fingers crossed', 'hope'], category: 'Gestures' },
  { emoji: '🤟', name: 'love-you gesture', keywords: ['love', 'ily', 'rock'], category: 'Gestures' },
  { emoji: '🤘', name: 'sign of the horns', keywords: ['rock', 'metal', 'horns'], category: 'Gestures' },
  { emoji: '🤙', name: 'call me hand', keywords: ['call', 'shaka', 'hang loose'], category: 'Gestures' },
  { emoji: '👈', name: 'backhand index pointing left', keywords: ['left', 'point'], category: 'Gestures' },
  { emoji: '👉', name: 'backhand index pointing right', keywords: ['right', 'point'], category: 'Gestures' },
  { emoji: '👆', name: 'backhand index pointing up', keywords: ['up', 'point'], category: 'Gestures' },
  { emoji: '👇', name: 'backhand index pointing down', keywords: ['down', 'point'], category: 'Gestures' },
  { emoji: '☝️', name: 'index pointing up', keywords: ['up', 'point', 'one'], category: 'Gestures' },
  { emoji: '👌', name: 'OK hand', keywords: ['ok', 'okay', 'perfect'], category: 'Gestures' },
  { emoji: '🤌', name: 'pinched fingers', keywords: ['italian', 'chef kiss', 'perfect'], category: 'Gestures' },
  { emoji: '✊', name: 'raised fist', keywords: ['fist', 'power', 'solidarity'], category: 'Gestures' },
  { emoji: '👊', name: 'oncoming fist', keywords: ['punch', 'fist bump'], category: 'Gestures' },
  { emoji: '🤛', name: 'left-facing fist', keywords: ['fist', 'bump'], category: 'Gestures' },
  { emoji: '🤜', name: 'right-facing fist', keywords: ['fist', 'bump'], category: 'Gestures' },
  { emoji: '✋', name: 'raised hand', keywords: ['stop', 'high five', 'hand'], category: 'Gestures' },
  { emoji: '🖐', name: 'hand with fingers splayed', keywords: ['hand', 'five'], category: 'Gestures' },
  { emoji: '🖖', name: 'vulcan salute', keywords: ['spock', 'star trek', 'vulcan'], category: 'Gestures' },
  { emoji: '👋', name: 'waving hand', keywords: ['wave', 'hello', 'goodbye', 'hi', 'bye'], category: 'Gestures' },
  { emoji: '🤚', name: 'raised back of hand', keywords: ['hand', 'stop'], category: 'Gestures' },
  { emoji: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle', 'arm', 'workout'], category: 'Gestures' },
  { emoji: '🖕', name: 'middle finger', keywords: ['finger', 'rude'], category: 'Gestures' },
  { emoji: '✍️', name: 'writing hand', keywords: ['write', 'pen'], category: 'Gestures' },
  { emoji: '🤳', name: 'selfie', keywords: ['selfie', 'phone', 'camera'], category: 'Gestures' },

  // Hearts & Love
  { emoji: '❤️', name: 'red heart', keywords: ['love', 'heart', 'red'], category: 'Symbols' },
  { emoji: '🧡', name: 'orange heart', keywords: ['love', 'heart', 'orange'], category: 'Symbols' },
  { emoji: '💛', name: 'yellow heart', keywords: ['love', 'heart', 'yellow'], category: 'Symbols' },
  { emoji: '💚', name: 'green heart', keywords: ['love', 'heart', 'green'], category: 'Symbols' },
  { emoji: '💙', name: 'blue heart', keywords: ['love', 'heart', 'blue'], category: 'Symbols' },
  { emoji: '💜', name: 'purple heart', keywords: ['love', 'heart', 'purple'], category: 'Symbols' },
  { emoji: '🖤', name: 'black heart', keywords: ['love', 'heart', 'black'], category: 'Symbols' },
  { emoji: '🤍', name: 'white heart', keywords: ['love', 'heart', 'white'], category: 'Symbols' },
  { emoji: '🤎', name: 'brown heart', keywords: ['love', 'heart', 'brown'], category: 'Symbols' },
  { emoji: '💔', name: 'broken heart', keywords: ['heartbreak', 'sad', 'broken'], category: 'Symbols' },
  { emoji: '❣️', name: 'heart exclamation', keywords: ['love', 'heart'], category: 'Symbols' },
  { emoji: '💕', name: 'two hearts', keywords: ['love', 'hearts'], category: 'Symbols' },
  { emoji: '💞', name: 'revolving hearts', keywords: ['love', 'hearts'], category: 'Symbols' },
  { emoji: '💓', name: 'beating heart', keywords: ['love', 'heart', 'beat'], category: 'Symbols' },
  { emoji: '💗', name: 'growing heart', keywords: ['love', 'heart'], category: 'Symbols' },
  { emoji: '💖', name: 'sparkling heart', keywords: ['love', 'heart', 'sparkle'], category: 'Symbols' },
  { emoji: '💘', name: 'heart with arrow', keywords: ['love', 'cupid', 'valentine'], category: 'Symbols' },
  { emoji: '💝', name: 'heart with ribbon', keywords: ['love', 'gift', 'valentine'], category: 'Symbols' },
  { emoji: '💟', name: 'heart decoration', keywords: ['love', 'heart'], category: 'Symbols' },
  { emoji: '💋', name: 'kiss mark', keywords: ['kiss', 'lips', 'love'], category: 'Symbols' },
  { emoji: '💯', name: 'hundred points', keywords: ['perfect', '100', 'score'], category: 'Symbols' },
  { emoji: '💢', name: 'anger symbol', keywords: ['angry', 'mad'], category: 'Symbols' },
  { emoji: '💥', name: 'collision', keywords: ['boom', 'explosion', 'crash'], category: 'Symbols' },
  { emoji: '💫', name: 'dizzy', keywords: ['star', 'dizzy', 'sparkle'], category: 'Symbols' },
  { emoji: '💦', name: 'sweat droplets', keywords: ['water', 'sweat', 'splash'], category: 'Symbols' },
  { emoji: '💨', name: 'dashing away', keywords: ['wind', 'fast', 'running'], category: 'Symbols' },
  { emoji: '🔥', name: 'fire', keywords: ['hot', 'flame', 'lit', 'fire'], category: 'Symbols' },
  { emoji: '✨', name: 'sparkles', keywords: ['sparkle', 'star', 'shine', 'magic'], category: 'Symbols' },
  { emoji: '⭐', name: 'star', keywords: ['star', 'favorite'], category: 'Symbols' },
  { emoji: '🌟', name: 'glowing star', keywords: ['star', 'glow', 'shine'], category: 'Symbols' },
  { emoji: '💬', name: 'speech balloon', keywords: ['chat', 'message', 'talk'], category: 'Symbols' },
  { emoji: '💭', name: 'thought balloon', keywords: ['think', 'thought'], category: 'Symbols' },
  { emoji: '🗯', name: 'right anger bubble', keywords: ['angry', 'speech'], category: 'Symbols' },
  { emoji: '💤', name: 'zzz', keywords: ['sleep', 'tired', 'snore'], category: 'Symbols' },

  // Activities & Celebration  
  { emoji: '🎉', name: 'party popper', keywords: ['party', 'celebrate', 'tada', 'congratulations'], category: 'Activities' },
  { emoji: '🎊', name: 'confetti ball', keywords: ['party', 'celebrate'], category: 'Activities' },
  { emoji: '🎈', name: 'balloon', keywords: ['party', 'birthday', 'balloon'], category: 'Activities' },
  { emoji: '🎁', name: 'wrapped gift', keywords: ['gift', 'present', 'birthday'], category: 'Activities' },
  { emoji: '🎂', name: 'birthday cake', keywords: ['birthday', 'cake', 'celebrate'], category: 'Activities' },
  { emoji: '🎄', name: 'Christmas tree', keywords: ['christmas', 'holiday', 'tree', 'xmas'], category: 'Activities' },
  { emoji: '🎅', name: 'Santa Claus', keywords: ['santa', 'christmas', 'holiday', 'xmas', 'father christmas', 'saint nick'], category: 'Activities' },
  { emoji: '🤶', name: 'Mrs. Claus', keywords: ['santa', 'christmas', 'holiday', 'xmas', 'mother christmas'], category: 'Activities' },
  { emoji: '🦌', name: 'deer', keywords: ['deer', 'reindeer', 'rudolph', 'christmas', 'santa'], category: 'Activities' },
  { emoji: '🛷', name: 'sled', keywords: ['sled', 'sledge', 'sleigh', 'christmas', 'santa', 'snow', 'winter'], category: 'Activities' },
  { emoji: '🎁', name: 'wrapped gift', keywords: ['gift', 'present', 'birthday', 'christmas', 'xmas'], category: 'Activities' },
  { emoji: '⛄', name: 'snowman without snow', keywords: ['snowman', 'winter', 'christmas', 'frosty', 'cold'], category: 'Activities' },
  { emoji: '🌟', name: 'glowing star', keywords: ['star', 'christmas', 'tree topper', 'shine', 'bright'], category: 'Activities' },
  { emoji: '🔔', name: 'bell', keywords: ['bell', 'christmas', 'jingle', 'ring', 'notification'], category: 'Activities' },
  { emoji: '🕯️', name: 'candle', keywords: ['candle', 'christmas', 'light', 'holiday'], category: 'Activities' },
  { emoji: '🧦', name: 'sock', keywords: ['sock', 'stocking', 'christmas', 'xmas'], category: 'Activities' },
  { emoji: '🧝', name: 'elf', keywords: ['elf', 'christmas', 'santa', 'helper', 'fantasy'], category: 'Activities' },
  { emoji: '🎃', name: 'jack-o-lantern', keywords: ['halloween', 'pumpkin'], category: 'Activities' },
  { emoji: '🎆', name: 'fireworks', keywords: ['fireworks', 'celebrate'], category: 'Activities' },
  { emoji: '🎇', name: 'sparkler', keywords: ['fireworks', 'sparkle'], category: 'Activities' },
  { emoji: '🏆', name: 'trophy', keywords: ['win', 'winner', 'champion', 'award'], category: 'Activities' },
  { emoji: '🥇', name: 'gold medal', keywords: ['first', 'gold', 'winner'], category: 'Activities' },
  { emoji: '🥈', name: 'silver medal', keywords: ['second', 'silver'], category: 'Activities' },
  { emoji: '🥉', name: 'bronze medal', keywords: ['third', 'bronze'], category: 'Activities' },
  { emoji: '⚽', name: 'soccer ball', keywords: ['soccer', 'football', 'sports'], category: 'Activities' },
  { emoji: '🏀', name: 'basketball', keywords: ['basketball', 'sports'], category: 'Activities' },
  { emoji: '🏈', name: 'american football', keywords: ['football', 'sports'], category: 'Activities' },
  { emoji: '⚾', name: 'baseball', keywords: ['baseball', 'sports'], category: 'Activities' },
  { emoji: '🎾', name: 'tennis', keywords: ['tennis', 'sports'], category: 'Activities' },
  { emoji: '🎮', name: 'video game', keywords: ['game', 'controller', 'gaming'], category: 'Activities' },
  { emoji: '🎯', name: 'direct hit', keywords: ['target', 'bullseye', 'dart'], category: 'Activities' },
  { emoji: '🎵', name: 'musical note', keywords: ['music', 'note', 'song'], category: 'Activities' },
  { emoji: '🎶', name: 'musical notes', keywords: ['music', 'notes', 'song'], category: 'Activities' },
  { emoji: '🎤', name: 'microphone', keywords: ['sing', 'karaoke', 'mic'], category: 'Activities' },
  { emoji: '🎧', name: 'headphone', keywords: ['music', 'headphones', 'listen'], category: 'Activities' },
  { emoji: '🎬', name: 'clapper board', keywords: ['movie', 'film', 'action'], category: 'Activities' },
  { emoji: '📸', name: 'camera with flash', keywords: ['photo', 'camera', 'picture'], category: 'Activities' },

  // Animals
  { emoji: '🐶', name: 'dog face', keywords: ['dog', 'puppy', 'pet'], category: 'Animals' },
  { emoji: '🐱', name: 'cat face', keywords: ['cat', 'kitten', 'pet'], category: 'Animals' },
  { emoji: '🐭', name: 'mouse face', keywords: ['mouse', 'rat'], category: 'Animals' },
  { emoji: '🐹', name: 'hamster', keywords: ['hamster', 'pet'], category: 'Animals' },
  { emoji: '🐰', name: 'rabbit face', keywords: ['rabbit', 'bunny'], category: 'Animals' },
  { emoji: '🦊', name: 'fox', keywords: ['fox'], category: 'Animals' },
  { emoji: '🐻', name: 'bear', keywords: ['bear'], category: 'Animals' },
  { emoji: '🐼', name: 'panda', keywords: ['panda', 'bear'], category: 'Animals' },
  { emoji: '🐨', name: 'koala', keywords: ['koala'], category: 'Animals' },
  { emoji: '🐯', name: 'tiger face', keywords: ['tiger'], category: 'Animals' },
  { emoji: '🦁', name: 'lion', keywords: ['lion', 'king'], category: 'Animals' },
  { emoji: '🐮', name: 'cow face', keywords: ['cow'], category: 'Animals' },
  { emoji: '🐷', name: 'pig face', keywords: ['pig'], category: 'Animals' },
  { emoji: '🐸', name: 'frog', keywords: ['frog'], category: 'Animals' },
  { emoji: '🐵', name: 'monkey face', keywords: ['monkey', 'ape'], category: 'Animals' },
  { emoji: '🙈', name: 'see-no-evil monkey', keywords: ['monkey', 'see no evil', 'hide'], category: 'Animals' },
  { emoji: '🙉', name: 'hear-no-evil monkey', keywords: ['monkey', 'hear no evil'], category: 'Animals' },
  { emoji: '🙊', name: 'speak-no-evil monkey', keywords: ['monkey', 'speak no evil', 'oops'], category: 'Animals' },
  { emoji: '🐔', name: 'chicken', keywords: ['chicken', 'bird'], category: 'Animals' },
  { emoji: '🐧', name: 'penguin', keywords: ['penguin', 'bird'], category: 'Animals' },
  { emoji: '🐦', name: 'bird', keywords: ['bird'], category: 'Animals' },
  { emoji: '🦆', name: 'duck', keywords: ['duck', 'bird'], category: 'Animals' },
  { emoji: '🦅', name: 'eagle', keywords: ['eagle', 'bird'], category: 'Animals' },
  { emoji: '🦉', name: 'owl', keywords: ['owl', 'bird', 'wise'], category: 'Animals' },
  { emoji: '🦇', name: 'bat', keywords: ['bat'], category: 'Animals' },
  { emoji: '🐺', name: 'wolf', keywords: ['wolf'], category: 'Animals' },
  { emoji: '🐴', name: 'horse face', keywords: ['horse'], category: 'Animals' },
  { emoji: '🦄', name: 'unicorn', keywords: ['unicorn', 'magic'], category: 'Animals' },
  { emoji: '🐝', name: 'bee', keywords: ['bee', 'honey'], category: 'Animals' },
  { emoji: '🦋', name: 'butterfly', keywords: ['butterfly', 'insect'], category: 'Animals' },
  { emoji: '🐌', name: 'snail', keywords: ['snail', 'slow'], category: 'Animals' },
  { emoji: '🐛', name: 'bug', keywords: ['bug', 'insect'], category: 'Animals' },
  { emoji: '🐢', name: 'turtle', keywords: ['turtle', 'slow'], category: 'Animals' },
  { emoji: '🐍', name: 'snake', keywords: ['snake'], category: 'Animals' },
  { emoji: '🦎', name: 'lizard', keywords: ['lizard', 'reptile'], category: 'Animals' },
  { emoji: '🦖', name: 'T-Rex', keywords: ['dinosaur', 't-rex'], category: 'Animals' },
  { emoji: '🐙', name: 'octopus', keywords: ['octopus'], category: 'Animals' },
  { emoji: '🦑', name: 'squid', keywords: ['squid'], category: 'Animals' },
  { emoji: '🦐', name: 'shrimp', keywords: ['shrimp', 'prawn'], category: 'Animals' },
  { emoji: '🦀', name: 'crab', keywords: ['crab'], category: 'Animals' },
  { emoji: '🐡', name: 'blowfish', keywords: ['fish', 'blowfish'], category: 'Animals' },
  { emoji: '🐠', name: 'tropical fish', keywords: ['fish'], category: 'Animals' },
  { emoji: '🐟', name: 'fish', keywords: ['fish'], category: 'Animals' },
  { emoji: '🐬', name: 'dolphin', keywords: ['dolphin'], category: 'Animals' },
  { emoji: '🐳', name: 'spouting whale', keywords: ['whale'], category: 'Animals' },
  { emoji: '🐋', name: 'whale', keywords: ['whale'], category: 'Animals' },
  { emoji: '🦈', name: 'shark', keywords: ['shark'], category: 'Animals' },
  { emoji: '🐊', name: 'crocodile', keywords: ['crocodile', 'alligator'], category: 'Animals' },
  { emoji: '🐘', name: 'elephant', keywords: ['elephant'], category: 'Animals' },
  { emoji: '🦒', name: 'giraffe', keywords: ['giraffe'], category: 'Animals' },
  { emoji: '🐕', name: 'dog', keywords: ['dog', 'pet'], category: 'Animals' },
  { emoji: '🐈', name: 'cat', keywords: ['cat', 'pet'], category: 'Animals' },

  // Food & Drink
  { emoji: '🍏', name: 'green apple', keywords: ['apple', 'fruit'], category: 'Food' },
  { emoji: '🍎', name: 'red apple', keywords: ['apple', 'fruit'], category: 'Food' },
  { emoji: '🍐', name: 'pear', keywords: ['pear', 'fruit'], category: 'Food' },
  { emoji: '🍊', name: 'tangerine', keywords: ['orange', 'fruit'], category: 'Food' },
  { emoji: '🍋', name: 'lemon', keywords: ['lemon', 'fruit'], category: 'Food' },
  { emoji: '🍌', name: 'banana', keywords: ['banana', 'fruit'], category: 'Food' },
  { emoji: '🍉', name: 'watermelon', keywords: ['watermelon', 'fruit'], category: 'Food' },
  { emoji: '🍇', name: 'grapes', keywords: ['grapes', 'fruit'], category: 'Food' },
  { emoji: '🍓', name: 'strawberry', keywords: ['strawberry', 'fruit'], category: 'Food' },
  { emoji: '🍒', name: 'cherries', keywords: ['cherry', 'fruit'], category: 'Food' },
  { emoji: '🍑', name: 'peach', keywords: ['peach', 'fruit', 'butt'], category: 'Food' },
  { emoji: '🍍', name: 'pineapple', keywords: ['pineapple', 'fruit'], category: 'Food' },
  { emoji: '🥝', name: 'kiwi', keywords: ['kiwi', 'fruit'], category: 'Food' },
  { emoji: '🍅', name: 'tomato', keywords: ['tomato', 'vegetable'], category: 'Food' },
  { emoji: '🥑', name: 'avocado', keywords: ['avocado', 'guac'], category: 'Food' },
  { emoji: '🌶', name: 'hot pepper', keywords: ['pepper', 'spicy', 'hot'], category: 'Food' },
  { emoji: '🌽', name: 'corn', keywords: ['corn', 'vegetable'], category: 'Food' },
  { emoji: '🥕', name: 'carrot', keywords: ['carrot', 'vegetable'], category: 'Food' },
  { emoji: '🥔', name: 'potato', keywords: ['potato', 'vegetable'], category: 'Food' },
  { emoji: '🍞', name: 'bread', keywords: ['bread', 'toast'], category: 'Food' },
  { emoji: '🧀', name: 'cheese', keywords: ['cheese'], category: 'Food' },
  { emoji: '🥚', name: 'egg', keywords: ['egg'], category: 'Food' },
  { emoji: '🍳', name: 'cooking', keywords: ['egg', 'frying', 'breakfast'], category: 'Food' },
  { emoji: '🥓', name: 'bacon', keywords: ['bacon', 'breakfast'], category: 'Food' },
  { emoji: '🍗', name: 'poultry leg', keywords: ['chicken', 'meat'], category: 'Food' },
  { emoji: '🍖', name: 'meat on bone', keywords: ['meat', 'bbq'], category: 'Food' },
  { emoji: '🌭', name: 'hot dog', keywords: ['hotdog', 'sausage'], category: 'Food' },
  { emoji: '🍔', name: 'hamburger', keywords: ['burger', 'fast food'], category: 'Food' },
  { emoji: '🍟', name: 'french fries', keywords: ['fries', 'fast food'], category: 'Food' },
  { emoji: '🍕', name: 'pizza', keywords: ['pizza'], category: 'Food' },
  { emoji: '🌮', name: 'taco', keywords: ['taco', 'mexican'], category: 'Food' },
  { emoji: '🌯', name: 'burrito', keywords: ['burrito', 'mexican'], category: 'Food' },
  { emoji: '🍜', name: 'steaming bowl', keywords: ['ramen', 'noodles', 'soup'], category: 'Food' },
  { emoji: '🍝', name: 'spaghetti', keywords: ['pasta', 'spaghetti'], category: 'Food' },
  { emoji: '🍣', name: 'sushi', keywords: ['sushi', 'japanese'], category: 'Food' },
  { emoji: '🍱', name: 'bento box', keywords: ['bento', 'japanese', 'lunch'], category: 'Food' },
  { emoji: '🍩', name: 'doughnut', keywords: ['donut', 'dessert'], category: 'Food' },
  { emoji: '🍪', name: 'cookie', keywords: ['cookie', 'dessert'], category: 'Food' },
  { emoji: '🎂', name: 'birthday cake', keywords: ['cake', 'birthday', 'dessert'], category: 'Food' },
  { emoji: '🍰', name: 'shortcake', keywords: ['cake', 'dessert'], category: 'Food' },
  { emoji: '🍦', name: 'soft ice cream', keywords: ['ice cream', 'dessert'], category: 'Food' },
  { emoji: '🍨', name: 'ice cream', keywords: ['ice cream', 'dessert'], category: 'Food' },
  { emoji: '🍧', name: 'shaved ice', keywords: ['ice', 'dessert'], category: 'Food' },
  { emoji: '🍫', name: 'chocolate bar', keywords: ['chocolate', 'dessert'], category: 'Food' },
  { emoji: '🍬', name: 'candy', keywords: ['candy', 'sweet'], category: 'Food' },
  { emoji: '🍭', name: 'lollipop', keywords: ['candy', 'sweet'], category: 'Food' },
  { emoji: '☕', name: 'hot beverage', keywords: ['coffee', 'tea', 'hot'], category: 'Food' },
  { emoji: '🍵', name: 'teacup', keywords: ['tea', 'green tea'], category: 'Food' },
  { emoji: '🍺', name: 'beer mug', keywords: ['beer', 'drink', 'alcohol'], category: 'Food' },
  { emoji: '🍻', name: 'clinking beer mugs', keywords: ['beer', 'cheers', 'toast'], category: 'Food' },
  { emoji: '🥂', name: 'clinking glasses', keywords: ['cheers', 'toast', 'champagne'], category: 'Food' },
  { emoji: '🍷', name: 'wine glass', keywords: ['wine', 'drink'], category: 'Food' },
  { emoji: '🍸', name: 'cocktail glass', keywords: ['cocktail', 'martini', 'drink'], category: 'Food' },
  { emoji: '🍹', name: 'tropical drink', keywords: ['drink', 'cocktail'], category: 'Food' },

  // Travel & Places
  { emoji: '🚗', name: 'automobile', keywords: ['car', 'vehicle'], category: 'Travel' },
  { emoji: '🚕', name: 'taxi', keywords: ['taxi', 'cab', 'car'], category: 'Travel' },
  { emoji: '🚌', name: 'bus', keywords: ['bus', 'vehicle'], category: 'Travel' },
  { emoji: '✈️', name: 'airplane', keywords: ['plane', 'flight', 'travel'], category: 'Travel' },
  { emoji: '🚀', name: 'rocket', keywords: ['rocket', 'space'], category: 'Travel' },
  { emoji: '🛸', name: 'flying saucer', keywords: ['ufo', 'alien', 'space'], category: 'Travel' },
  { emoji: '🚁', name: 'helicopter', keywords: ['helicopter', 'chopper'], category: 'Travel' },
  { emoji: '⛵', name: 'sailboat', keywords: ['boat', 'sail'], category: 'Travel' },
  { emoji: '🚢', name: 'ship', keywords: ['ship', 'boat'], category: 'Travel' },
  { emoji: '🏠', name: 'house', keywords: ['house', 'home'], category: 'Travel' },
  { emoji: '🏢', name: 'office building', keywords: ['office', 'building', 'work'], category: 'Travel' },
  { emoji: '🏥', name: 'hospital', keywords: ['hospital', 'health'], category: 'Travel' },
  { emoji: '🏫', name: 'school', keywords: ['school', 'education'], category: 'Travel' },
  { emoji: '🏰', name: 'castle', keywords: ['castle'], category: 'Travel' },
  { emoji: '⛰', name: 'mountain', keywords: ['mountain'], category: 'Travel' },
  { emoji: '🏔', name: 'snow-capped mountain', keywords: ['mountain', 'snow'], category: 'Travel' },
  { emoji: '🌋', name: 'volcano', keywords: ['volcano'], category: 'Travel' },
  { emoji: '🏖', name: 'beach', keywords: ['beach', 'vacation'], category: 'Travel' },
  { emoji: '🏝', name: 'desert island', keywords: ['island', 'beach'], category: 'Travel' },
  { emoji: '🌅', name: 'sunrise', keywords: ['sunrise', 'morning'], category: 'Travel' },
  { emoji: '🌄', name: 'sunrise over mountains', keywords: ['sunrise', 'morning', 'mountain'], category: 'Travel' },
  { emoji: '🌃', name: 'night with stars', keywords: ['night', 'city', 'stars'], category: 'Travel' },
  { emoji: '🌉', name: 'bridge at night', keywords: ['bridge', 'night'], category: 'Travel' },
  { emoji: '🌌', name: 'milky way', keywords: ['space', 'galaxy', 'stars'], category: 'Travel' },
  { emoji: '🌍', name: 'globe europe-africa', keywords: ['earth', 'world', 'globe'], category: 'Travel' },
  { emoji: '🌎', name: 'globe americas', keywords: ['earth', 'world', 'globe'], category: 'Travel' },
  { emoji: '🌏', name: 'globe asia-australia', keywords: ['earth', 'world', 'globe'], category: 'Travel' },
  { emoji: '🌙', name: 'crescent moon', keywords: ['moon', 'night'], category: 'Travel' },
  { emoji: '☀️', name: 'sun', keywords: ['sun', 'sunny', 'hot'], category: 'Travel' },
  { emoji: '⛅', name: 'sun behind cloud', keywords: ['cloudy', 'weather'], category: 'Travel' },
  { emoji: '☁️', name: 'cloud', keywords: ['cloud', 'weather'], category: 'Travel' },
  { emoji: '🌧', name: 'cloud with rain', keywords: ['rain', 'weather'], category: 'Travel' },
  { emoji: '⛈', name: 'cloud with lightning and rain', keywords: ['storm', 'weather'], category: 'Travel' },
  { emoji: '🌈', name: 'rainbow', keywords: ['rainbow'], category: 'Travel' },
  { emoji: '❄️', name: 'snowflake', keywords: ['snow', 'cold', 'winter'], category: 'Travel' },
  { emoji: '☃️', name: 'snowman', keywords: ['snow', 'winter'], category: 'Travel' },

  // Objects
  { emoji: '⌚', name: 'watch', keywords: ['watch', 'time'], category: 'Objects' },
  { emoji: '📱', name: 'mobile phone', keywords: ['phone', 'mobile', 'cell'], category: 'Objects' },
  { emoji: '💻', name: 'laptop', keywords: ['laptop', 'computer'], category: 'Objects' },
  { emoji: '🖥', name: 'desktop computer', keywords: ['computer', 'desktop'], category: 'Objects' },
  { emoji: '🖨', name: 'printer', keywords: ['printer'], category: 'Objects' },
  { emoji: '⌨️', name: 'keyboard', keywords: ['keyboard', 'type'], category: 'Objects' },
  { emoji: '🖱', name: 'computer mouse', keywords: ['mouse', 'click'], category: 'Objects' },
  { emoji: '💾', name: 'floppy disk', keywords: ['save', 'floppy'], category: 'Objects' },
  { emoji: '💿', name: 'optical disk', keywords: ['cd', 'disk'], category: 'Objects' },
  { emoji: '📷', name: 'camera', keywords: ['camera', 'photo'], category: 'Objects' },
  { emoji: '📹', name: 'video camera', keywords: ['video', 'camera'], category: 'Objects' },
  { emoji: '📺', name: 'television', keywords: ['tv', 'television'], category: 'Objects' },
  { emoji: '📻', name: 'radio', keywords: ['radio'], category: 'Objects' },
  { emoji: '🔋', name: 'battery', keywords: ['battery', 'power'], category: 'Objects' },
  { emoji: '🔌', name: 'electric plug', keywords: ['plug', 'power'], category: 'Objects' },
  { emoji: '💡', name: 'light bulb', keywords: ['idea', 'light', 'bulb'], category: 'Objects' },
  { emoji: '🔦', name: 'flashlight', keywords: ['flashlight', 'torch'], category: 'Objects' },
  { emoji: '📚', name: 'books', keywords: ['books', 'read', 'study'], category: 'Objects' },
  { emoji: '📖', name: 'open book', keywords: ['book', 'read'], category: 'Objects' },
  { emoji: '📝', name: 'memo', keywords: ['note', 'write', 'memo'], category: 'Objects' },
  { emoji: '✏️', name: 'pencil', keywords: ['pencil', 'write'], category: 'Objects' },
  { emoji: '🖊', name: 'pen', keywords: ['pen', 'write'], category: 'Objects' },
  { emoji: '📎', name: 'paperclip', keywords: ['paperclip', 'attachment'], category: 'Objects' },
  { emoji: '📌', name: 'pushpin', keywords: ['pin', 'location'], category: 'Objects' },
  { emoji: '✂️', name: 'scissors', keywords: ['scissors', 'cut'], category: 'Objects' },
  { emoji: '🔒', name: 'locked', keywords: ['lock', 'secure'], category: 'Objects' },
  { emoji: '🔓', name: 'unlocked', keywords: ['unlock', 'open'], category: 'Objects' },
  { emoji: '🔑', name: 'key', keywords: ['key'], category: 'Objects' },
  { emoji: '🔨', name: 'hammer', keywords: ['hammer', 'tool'], category: 'Objects' },
  { emoji: '🔧', name: 'wrench', keywords: ['wrench', 'tool'], category: 'Objects' },
  { emoji: '🔩', name: 'nut and bolt', keywords: ['bolt', 'tool'], category: 'Objects' },
  { emoji: '⚙️', name: 'gear', keywords: ['gear', 'settings'], category: 'Objects' },
  { emoji: '💊', name: 'pill', keywords: ['pill', 'medicine'], category: 'Objects' },
  { emoji: '💉', name: 'syringe', keywords: ['needle', 'shot', 'vaccine'], category: 'Objects' },
  { emoji: '🚽', name: 'toilet', keywords: ['toilet', 'bathroom'], category: 'Objects' },
  { emoji: '🚿', name: 'shower', keywords: ['shower', 'bathroom'], category: 'Objects' },
  { emoji: '🛁', name: 'bathtub', keywords: ['bath', 'tub'], category: 'Objects' },
  { emoji: '🧴', name: 'lotion bottle', keywords: ['lotion', 'cream'], category: 'Objects' },
  { emoji: '🧷', name: 'safety pin', keywords: ['pin'], category: 'Objects' },
  { emoji: '🧹', name: 'broom', keywords: ['broom', 'sweep', 'clean'], category: 'Objects' },
  { emoji: '🧺', name: 'basket', keywords: ['basket', 'laundry'], category: 'Objects' },
  { emoji: '🧻', name: 'roll of paper', keywords: ['toilet paper', 'tp'], category: 'Objects' },
  { emoji: '🧼', name: 'soap', keywords: ['soap', 'clean'], category: 'Objects' },
  { emoji: '🧽', name: 'sponge', keywords: ['sponge', 'clean'], category: 'Objects' },
  { emoji: '💰', name: 'money bag', keywords: ['money', 'rich', 'dollar'], category: 'Objects' },
  { emoji: '💵', name: 'dollar banknote', keywords: ['money', 'dollar', 'cash'], category: 'Objects' },
  { emoji: '💳', name: 'credit card', keywords: ['credit', 'card', 'payment'], category: 'Objects' },
  { emoji: '💎', name: 'gem stone', keywords: ['diamond', 'gem', 'jewel'], category: 'Objects' },

  // More symbols
  { emoji: '✅', name: 'check mark button', keywords: ['check', 'done', 'yes'], category: 'Symbols' },
  { emoji: '❌', name: 'cross mark', keywords: ['no', 'wrong', 'x'], category: 'Symbols' },
  { emoji: '❓', name: 'question mark', keywords: ['question', 'what'], category: 'Symbols' },
  { emoji: '❗', name: 'exclamation mark', keywords: ['exclamation', 'important'], category: 'Symbols' },
  { emoji: '⚠️', name: 'warning', keywords: ['warning', 'caution'], category: 'Symbols' },
  { emoji: '🚫', name: 'prohibited', keywords: ['no', 'forbidden', 'stop'], category: 'Symbols' },
  { emoji: '♻️', name: 'recycling symbol', keywords: ['recycle', 'green'], category: 'Symbols' },
  { emoji: '✔️', name: 'check mark', keywords: ['check', 'yes', 'done'], category: 'Symbols' },
  { emoji: '➡️', name: 'right arrow', keywords: ['arrow', 'right', 'next'], category: 'Symbols' },
  { emoji: '⬅️', name: 'left arrow', keywords: ['arrow', 'left', 'back'], category: 'Symbols' },
  { emoji: '⬆️', name: 'up arrow', keywords: ['arrow', 'up'], category: 'Symbols' },
  { emoji: '⬇️', name: 'down arrow', keywords: ['arrow', 'down'], category: 'Symbols' },
  { emoji: '🔄', name: 'counterclockwise arrows button', keywords: ['refresh', 'reload', 'sync'], category: 'Symbols' },
  { emoji: '🔀', name: 'shuffle tracks button', keywords: ['shuffle', 'random'], category: 'Symbols' },
  { emoji: '🔁', name: 'repeat button', keywords: ['repeat', 'loop'], category: 'Symbols' },
  { emoji: '➕', name: 'plus', keywords: ['plus', 'add'], category: 'Symbols' },
  { emoji: '➖', name: 'minus', keywords: ['minus', 'subtract'], category: 'Symbols' },
  { emoji: '➗', name: 'divide', keywords: ['divide', 'division'], category: 'Symbols' },
  { emoji: '✖️', name: 'multiply', keywords: ['multiply', 'x'], category: 'Symbols' },
  { emoji: '♾️', name: 'infinity', keywords: ['infinity', 'forever'], category: 'Symbols' },
  { emoji: '💲', name: 'dollar sign', keywords: ['dollar', 'money'], category: 'Symbols' },
  { emoji: '©️', name: 'copyright', keywords: ['copyright'], category: 'Symbols' },
  { emoji: '®️', name: 'registered', keywords: ['registered', 'trademark'], category: 'Symbols' },
  { emoji: '™️', name: 'trade mark', keywords: ['trademark'], category: 'Symbols' },
  { emoji: '#️⃣', name: 'keycap hash', keywords: ['hashtag', 'number'], category: 'Symbols' },
  { emoji: '*️⃣', name: 'keycap asterisk', keywords: ['asterisk', 'star'], category: 'Symbols' },
  { emoji: '0️⃣', name: 'keycap 0', keywords: ['zero', '0'], category: 'Symbols' },
  { emoji: '1️⃣', name: 'keycap 1', keywords: ['one', '1'], category: 'Symbols' },
  { emoji: '2️⃣', name: 'keycap 2', keywords: ['two', '2'], category: 'Symbols' },
  { emoji: '3️⃣', name: 'keycap 3', keywords: ['three', '3'], category: 'Symbols' },
  { emoji: '4️⃣', name: 'keycap 4', keywords: ['four', '4'], category: 'Symbols' },
  { emoji: '5️⃣', name: 'keycap 5', keywords: ['five', '5'], category: 'Symbols' },
  { emoji: '6️⃣', name: 'keycap 6', keywords: ['six', '6'], category: 'Symbols' },
  { emoji: '7️⃣', name: 'keycap 7', keywords: ['seven', '7'], category: 'Symbols' },
  { emoji: '8️⃣', name: 'keycap 8', keywords: ['eight', '8'], category: 'Symbols' },
  { emoji: '9️⃣', name: 'keycap 9', keywords: ['nine', '9'], category: 'Symbols' },
  { emoji: '🔟', name: 'keycap 10', keywords: ['ten', '10'], category: 'Symbols' },
  { emoji: '🔴', name: 'red circle', keywords: ['red', 'circle'], category: 'Symbols' },
  { emoji: '🟠', name: 'orange circle', keywords: ['orange', 'circle'], category: 'Symbols' },
  { emoji: '🟡', name: 'yellow circle', keywords: ['yellow', 'circle'], category: 'Symbols' },
  { emoji: '🟢', name: 'green circle', keywords: ['green', 'circle'], category: 'Symbols' },
  { emoji: '🔵', name: 'blue circle', keywords: ['blue', 'circle'], category: 'Symbols' },
  { emoji: '🟣', name: 'purple circle', keywords: ['purple', 'circle'], category: 'Symbols' },
  { emoji: '🟤', name: 'brown circle', keywords: ['brown', 'circle'], category: 'Symbols' },
  { emoji: '⚫', name: 'black circle', keywords: ['black', 'circle'], category: 'Symbols' },
  { emoji: '⚪', name: 'white circle', keywords: ['white', 'circle'], category: 'Symbols' },
  { emoji: '🟥', name: 'red square', keywords: ['red', 'square'], category: 'Symbols' },
  { emoji: '🟧', name: 'orange square', keywords: ['orange', 'square'], category: 'Symbols' },
  { emoji: '🟨', name: 'yellow square', keywords: ['yellow', 'square'], category: 'Symbols' },
  { emoji: '🟩', name: 'green square', keywords: ['green', 'square'], category: 'Symbols' },
  { emoji: '🟦', name: 'blue square', keywords: ['blue', 'square'], category: 'Symbols' },
  { emoji: '🟪', name: 'purple square', keywords: ['purple', 'square'], category: 'Symbols' },
  { emoji: '⬛', name: 'black large square', keywords: ['black', 'square'], category: 'Symbols' },
  { emoji: '⬜', name: 'white large square', keywords: ['white', 'square'], category: 'Symbols' },
];

// Search function
export function searchEmojis(query: string): EmojiData[] {
  if (!query.trim()) {
    return EMOJIS;
  }
  
  const lowerQuery = query.toLowerCase().trim();
  
  return EMOJIS.filter(emoji => 
    emoji.name.toLowerCase().includes(lowerQuery) ||
    emoji.keywords.some(keyword => keyword.toLowerCase().includes(lowerQuery)) ||
    emoji.category.toLowerCase().includes(lowerQuery)
  );
}

// Get emojis by category
export function getEmojisByCategory(category: EmojiCategory): EmojiData[] {
  if (category === 'Frequently Used') {
    return FREQUENT_EMOJIS.map(emoji => 
      EMOJIS.find(e => e.emoji === emoji) || { emoji, name: '', keywords: [], category: 'Frequently Used' }
    );
  }
  return EMOJIS.filter(emoji => emoji.category === category);
}

